---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: tracker/busyboxplus
    tag: ruby-git

inputs:
- name: concourse-branch-manager
- name: git-branches
- name: template-repo
- name: config-repo
- name: credentials-repo

params:
  CONCOURSE_URL: null
  CONCOURSE_USERNAME: null
  CONCOURSE_PASSWORD: null
  CONCOURSE_TEAM: null

run:
  path: concourse-branch-manager/tasks/manage_branches.rb
